
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.syntactic;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int BIT_XOR = 53;
  public static final int SHR_ASSIGN = 36;
  public static final int SHR = 57;
  public static final int DIVIDE = 26;
  public static final int CHARCONTENT = 61;
  public static final int XOR_ASSIGN = 38;
  public static final int SHL = 56;
  public static final int CHAR = 3;
  public static final int GE = 50;
  public static final int BIT_NOT = 55;
  public static final int BIT_AND = 54;
  public static final int LPAREN = 15;
  public static final int SEMI = 21;
  public static final int CONTINUE = 11;
  public static final int INT = 4;
  public static final int FOR = 10;
  public static final int MINUS = 24;
  public static final int RPAREN = 16;
  public static final int AND = 42;
  public static final int NOT = 40;
  public static final int SUB_ASSIGN = 34;
  public static final int SIZEOF = 14;
  public static final int LT = 47;
  public static final int OR = 41;
  public static final int COMMA = 22;
  public static final int INC = 28;
  public static final int NUM = 59;
  public static final int PLUS = 23;
  public static final int ASSIGN = 51;
  public static final int IF = 7;
  public static final int ID = 58;
  public static final int PTR = 44;
  public static final int DOT = 43;
  public static final int LE = 48;
  public static final int ADD_ASSIGN = 33;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 35;
  public static final int BREAK = 12;
  public static final int VOID = 2;
  public static final int EQ = 45;
  public static final int DIV_ASSIGN = 31;
  public static final int MOD_ASSIGN = 32;
  public static final int MODULE = 27;
  public static final int TIMES = 25;
  public static final int UNION = 6;
  public static final int LBRACE = 17;
  public static final int ELSE = 8;
  public static final int AND_ASSIGN = 37;
  public static final int WHILE = 9;
  public static final int OR_ASSIGN = 39;
  public static final int RBRACE = 18;
  public static final int NE = 46;
  public static final int MUL_ASSIGN = 30;
  public static final int RMPAREN = 20;
  public static final int LMPAREN = 19;
  public static final int BIT_OR = 52;
  public static final int DEC = 29;
  public static final int STRUCT = 5;
  public static final int STRINGCONTENT = 60;
  public static final int GT = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "CHAR",
  "INT",
  "STRUCT",
  "UNION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "CONTINUE",
  "BREAK",
  "RETURN",
  "SIZEOF",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LMPAREN",
  "RMPAREN",
  "SEMI",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODULE",
  "INC",
  "DEC",
  "MUL_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "ADD_ASSIGN",
  "SUB_ASSIGN",
  "SHL_ASSIGN",
  "SHR_ASSIGN",
  "AND_ASSIGN",
  "XOR_ASSIGN",
  "OR_ASSIGN",
  "NOT",
  "OR",
  "AND",
  "DOT",
  "PTR",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "ASSIGN",
  "BIT_OR",
  "BIT_XOR",
  "BIT_AND",
  "BIT_NOT",
  "SHL",
  "SHR",
  "ID",
  "NUM",
  "STRINGCONTENT",
  "CHARCONTENT"
  };
}

